server:
  port: 8082

spring:
  datasource:
    url: ${ACCOUNT_DB_URL:jdbc:postgresql://localhost:5432/account_db}

banking:
  account:
    supported-currencies: [INR, USD, EUR, GBP]
    default-currency: INR
    daily-balance-snapshot-cron: "0 5 0 * * *"
    inactive-account-days: 365
  events:
    account-events-topic: banking.account.events.v1
    balance-events-topic: banking.account.balance.v1

