server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_LABEL:main}
          clone-on-start: true
          force-pull: true
          timeout: 10
          username: ${CONFIG_GIT_USERNAME:}
          password: ${CONFIG_GIT_TOKEN:}
        encrypt:
          enabled: false
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

